micronaut:
    application:
        name: topfarming
    caches:
        my-cache: # <1>
            charset: 'UTF-8'
    jcache:
        enabled: false
application:
    max: 50
datasources:
    default:
        url: ${JDBC_URL:`jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}
        username: ${JDBC_USER:sa}
        password: ${JDBC_PASSWORD:""}
        schema-generate: CREATE_DROP
        dialect: H2
jpa:
    default:
        packages-to-scan:
        - 'topfarming.poc.domain'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
redis:
    uri: redis://localhost:7001/0
    ssl: true
    timeout: 30s
    caches:
        my-cache:
            # expire one hour after write
            expire-after-write: 1h
            key-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer
            value-serializer: io.micronaut.jackson.serialize.JacksonObjectSerializer
    servers:
        default:
            uri: redis://localhost:7001/1
            ssl: true
            timeout: 30s
        entity:
            uri: redis://localhost:7001/2
            ssl: true
            timeout: 30s